# coding: utf-8

"""
    DNS Data API

    The DNS Data is a BloxOne DDI service providing primary authoritative zone support. DNS Data is authoritative for all DNS resource records and is acting as a primary DNS server. It is part of the full-featured, DDI cloud solution that enables customers to deploy large numbers of protocol servers to deliver DNS and DHCP throughout their enterprise network.    # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bloxonednsdata
from bloxonednsdata.api.record_api import RecordApi  # noqa: E501
from bloxonednsdata.rest import ApiException


class TestRecordApi(unittest.TestCase):
    """RecordApi unit test stubs"""

    def setUp(self):
        self.api = bloxonednsdata.api.record_api.RecordApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_record_create(self):
        """Test case for record_create

        Create the Record object.  # noqa: E501
        """
        pass

    def test_record_delete(self):
        """Test case for record_delete

        Delete the Record object.  # noqa: E501
        """
        pass

    def test_record_list(self):
        """Test case for record_list

        List the Record objects.  # noqa: E501
        """
        pass

    def test_record_read(self):
        """Test case for record_read

        Read the Record object.  # noqa: E501
        """
        pass

    def test_record_soa_serial_increment(self):
        """Test case for record_soa_serial_increment

        SOA serial increment  # noqa: E501
        """
        pass

    def test_record_update(self):
        """Test case for record_update

        Update the Record object.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
