# coding: utf-8

# flake8: noqa
"""
    DNS Data API

    The DNS Data is a BloxOne DDI service providing primary authoritative zone support. DNS Data is authoritative for all DNS resource records and is acting as a primary DNS server. It is part of the full-featured, DDI cloud solution that enables customers to deploy large numbers of protocol servers to deliver DNS and DHCP throughout their enterprise network.    # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from bloxonednsdata.models.data_create_record_response import DataCreateRecordResponse
from bloxonednsdata.models.data_list_record_response import DataListRecordResponse
from bloxonednsdata.models.data_read_record_response import DataReadRecordResponse
from bloxonednsdata.models.data_record import DataRecord
from bloxonednsdata.models.data_record_inheritance import DataRecordInheritance
from bloxonednsdata.models.data_soa_serial_increment_request import DataSOASerialIncrementRequest
from bloxonednsdata.models.data_soa_serial_increment_response import DataSOASerialIncrementResponse
from bloxonednsdata.models.data_update_record_response import DataUpdateRecordResponse
from bloxonednsdata.models.inheritance2_inherited_u_int32 import Inheritance2InheritedUInt32
from bloxonednsdata.models.protobuf_field_mask import ProtobufFieldMask
from bloxonednsdata.models.types_json_value import TypesJSONValue
