# coding: utf-8

"""
    DNS Data API

    The DNS Data is a BloxOne DDI service providing primary authoritative zone support. DNS Data is authoritative for all DNS resource records and is acting as a primary DNS server. It is part of the full-featured, DDI cloud solution that enables customers to deploy large numbers of protocol servers to deliver DNS and DHCP throughout their enterprise network.    # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DataSOASerialIncrementRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fields': 'ProtobufFieldMask',
        'id': 'str',
        'serial_increment': 'int'
    }

    attribute_map = {
        'fields': 'fields',
        'id': 'id',
        'serial_increment': 'serial_increment'
    }

    def __init__(self, fields=None, id=None, serial_increment=None):  # noqa: E501
        """DataSOASerialIncrementRequest - a model defined in Swagger"""  # noqa: E501

        self._fields = None
        self._id = None
        self._serial_increment = None
        self.discriminator = None

        if fields is not None:
            self.fields = fields
        if id is not None:
            self.id = id
        if serial_increment is not None:
            self.serial_increment = serial_increment

    @property
    def fields(self):
        """Gets the fields of this DataSOASerialIncrementRequest.  # noqa: E501


        :return: The fields of this DataSOASerialIncrementRequest.  # noqa: E501
        :rtype: ProtobufFieldMask
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this DataSOASerialIncrementRequest.


        :param fields: The fields of this DataSOASerialIncrementRequest.  # noqa: E501
        :type: ProtobufFieldMask
        """

        self._fields = fields

    @property
    def id(self):
        """Gets the id of this DataSOASerialIncrementRequest.  # noqa: E501

        The resource identifier.  # noqa: E501

        :return: The id of this DataSOASerialIncrementRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DataSOASerialIncrementRequest.

        The resource identifier.  # noqa: E501

        :param id: The id of this DataSOASerialIncrementRequest.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def serial_increment(self):
        """Gets the serial_increment of this DataSOASerialIncrementRequest.  # noqa: E501

        Optional. Default increment SOA serial number by 1,000.  # noqa: E501

        :return: The serial_increment of this DataSOASerialIncrementRequest.  # noqa: E501
        :rtype: int
        """
        return self._serial_increment

    @serial_increment.setter
    def serial_increment(self, serial_increment):
        """Sets the serial_increment of this DataSOASerialIncrementRequest.

        Optional. Default increment SOA serial number by 1,000.  # noqa: E501

        :param serial_increment: The serial_increment of this DataSOASerialIncrementRequest.  # noqa: E501
        :type: int
        """

        self._serial_increment = serial_increment

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataSOASerialIncrementRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataSOASerialIncrementRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
